import { Data } from 'stores/FirebaseStore'
import { Timestamp } from 'firebase/firestore'

export const mangasData: Data[] = [
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		progress: '94x',
		name: 'Bastard (Hwang Youngchan)',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		progress: '81',
		name: 'Damn Reincarnation',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		progress: '74',
		name: 'Heavenly Inquisition Sword',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		name: 'Helmut: The Forsaken Child',
		progress: '40',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		progress: '35',
		name: 'Infinite Mage',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		progress: '137',
		name: 'Mercenary Enrollment',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		progress: '22',
		name: 'Revenge of the Iron-Blooded Sword Hound',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		progress: '61',
		name: 'Sleeping Ranker',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		progress: '200x',
		name: 'Solo Leveling',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		progress: '59',
		name: 'Superhuman Battlefield',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		name: 'Swordmaster’s Youngest Son',
		progress: '55',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		progress: '170x',
		name: 'The Demon King Who Lost His Job',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: 'Academy’s Genius Swordmaster',
		progress: '9',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: 'Arcane Sniper',
		progress: '68',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: 'Auto Hunting',
		progress: '54',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		progress: '3',
		name: 'Bones',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: 'Clever Cleaning Life Of The Returned Genius Hunter',
		progress: '44',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		progress: '235',
		name: 'Cultivator Against Hero Society',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: 'Dungeon Seeker',
		progress: '33x',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		progress: '72x',
		name: 'Existence',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		progress: '50',
		name: 'How a Former Pro takes advantage by doing an easy job',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		progress: '37',
		name: 'I Regressed to My Ruined Family',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		progress: '28',
		name: 'I Used To Be A Boss',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		progress: '57',
		name: "I'm not the Overlord!",
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		progress: '78',
		name: 'Kill the Dragon',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: 'Kill The hero',
		progress: '100',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		progress: '41',
		name: 'Leveling Up With Skills',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: 'Maxed Out Leveling',
		progress: '53',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		progress: '99',
		name: 'Memorize',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		progress: '43',
		name: 'My Civil Servant Life Reborn in the Strange World',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		progress: '99',
		name: 'Nano Machine',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		progress: '257',
		name: 'Peerless Dad',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		progress: '38',
		name: 'Player Who Returned 10,000 Years Later',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: 'Reborn as the Enemy Prince',
		progress: '29',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		progress: '60',
		name: 'Reincarnation Of The Suicidal Battle God',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: 'Return of the Disaster-Class Hero',
		progress: '42',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		progress: '49',
		name: 'Return of the Frozen Player',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		progress: '72',
		name: 'Return of the Mount Hua Sect',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		progress: '79',
		name: 'Solo Max-Level Newbie',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: 'Sss-Class Suicide Hunter',
		progress: '80',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: 'Standard of Reincarnation',
		progress: '31',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		progress: '141x',
		name: 'Sweet Home',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		progress: '258',
		name: 'Tales Of Demons And Gods',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: 'Terminally-Ill Genius Dark Knight',
		progress: '12',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: 'The Beginning After The End',
		progress: '175',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: 'The Eminence In Shadow',
		progress: '30',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: 'The Game That I Came From',
		progress: '153',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		progress: '86',
		name: 'The Greatest Estate Developer',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: 'The Heavenly Demon Can’t Live a Normal Life',
		progress: '63',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		progress: '6',
		name: 'The Knight King Who Returned with a God',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: 'The Max-Level Player’s 100th Regression',
		progress: '28',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: 'The S-Classes That I Raised',
		progress: '68',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: 'The Second Coming Of Gluttony',
		progress: '109',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: 'The Tutorial Tower Of The Advanced Player',
		progress: '142',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		progress: '95',
		name: 'Villain To Kill',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: 'Virtual World: Close Combat Mage',
		progress: '306',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: 'Warrior High School - Dungeon Raid Department',
		progress: '45',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		progress: '21',
		name: 'Absolute Sword Sense',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		progress: '7',
		name: 'Chronicles of the Demon Faction',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		name: 'Chronicles Of The Martial God’s Return',
		progress: '85',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		progress: '22',
		name: 'Dragon-Devouring Mage',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		name: 'Fff-Class Trashero',
		progress: '155',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		progress: '50',
		name: 'Genius of the Unique Lineage',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		name: 'Heavenly Demon Instructor',
		progress: '50',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		progress: '13',
		name: 'Heavenly Grand Archive’s Young Master',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		name: 'Heroes, Demons & Villains',
		progress: '50',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		name: 'I Obtained a Mythic Item',
		progress: '46',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		progress: '80',
		name: 'I Reincarnated As The Crazed Heir',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		name: 'I Returned as an FFF-Class Witch Doctor',
		progress: '6',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		progress: '15',
		name: 'I’m Not That Kind of Talent',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		name: 'Legend of Asura – The Venom Dragon',
		progress: '133',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		progress: '28',
		name: 'Legendary Ranker’s Comeback',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		name: 'Legendary Youngest Son of the Marquis House',
		progress: '61',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		name: 'Logging 10,000 Years into the Future',
		progress: '5',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		name: 'Magic Emperor',
		progress: '197',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		name: 'Martial God Regressed to Level 2',
		progress: '26',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		name: 'Maseki Gurume: Mamono no Chikara o Tabeta Ore wa Saikyou!',
		progress: '37',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		progress: '47x',
		name: 'MookHyang - The Origin',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		name: 'My Daughter is the Final Boss',
		progress: '70',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		progress: '18',
		name: 'My Insanely Competent Underlings',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		name: 'Nan Hao & Shang Feng',
		progress: '90',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		progress: '43x',
		name: 'On My Way to Kill God',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		progress: '109',
		name: 'Overgeared',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		name: 'Overpowered Sword',
		progress: '60',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		progress: '58',
		name: 'Path of the Shaman',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		progress: '39',
		name: 'Poison-Eating Healer',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		name: 'Regressing with the King’s Power',
		progress: '14',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		progress: '30',
		name: 'Return of the SSS-Class Ranker',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		name: 'Return of The Unrivaled Spear Knight',
		progress: '39',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		progress: '68x',
		name: 'Shotgun Boy',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		name: 'Surviving The Game as a Barbarian',
		progress: '7',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		progress: '62',
		name: 'The Constellation That Returned From Hell',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		name: 'The Dark Magician Transmigrates After 66666 Years',
		progress: '57',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		progress: '431',
		name: 'The Gamer',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		name: 'The Great Mage Returns After 4000 Years',
		progress: '147',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		progress: '66',
		name: 'The Live',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		name: 'The Tutorial is Too Hard',
		progress: '77',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		progress: '50',
		name: 'Transmigrating to the Otherworld Once More',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		name: 'Youngest Scion of the Mages',
		progress: '34',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'C',
		progress: '38',
		name: 'Academy’s Undercover Professor',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'C',
		progress: '43',
		name: 'Archmage Transcending Through Regression',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'C',
		name: 'Blaze Core',
		progress: '59',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'C',
		progress: '46',
		name: 'Everyone Else is A Returnee',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'C',
		name: 'Leviathan',
		progress: '132',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'C',
		name: 'Moshi Fanren',
		progress: '284',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'C',
		progress: '203',
		name: 'My Wife Is A Demon Queen',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'C',
		name: 'Omniscient Reader’s Viewpoint',
		progress: '155',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'C',
		progress: '83',
		name: 'Player who Can’t Level Up',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'C',
		name: 'Reformation of the Deadbeat Noble',
		progress: '84',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'C',
		name: 'The Dark Mage’s Return to Enlistment',
		progress: '31',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'C',
		progress: '32',
		name: 'The Guy Upstairs',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'C',
		progress: '32',
		name: 'The Max Level Hero Has Returned!',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'C',
		progress: '19',
		name: 'The Player Hides His Past',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'D',
		progress: '49',
		name: 'Astral Pet Store',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'D',
		name: 'Dungeon Odyssey',
		progress: '40',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'D',
		progress: '97',
		name: 'Dungeons & Artifacts',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'D',
		progress: '45',
		name: 'I Grow Stronger By Eating!',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'D',
		progress: '91',
		name: 'The Lord’s Coins Aren’t Decreasing?!',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		progress: '53',
		name: '3CM Hunter',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		name: 'Absolute Necromancer',
		progress: '12',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		name: 'Apotheosis',
		progress: '?',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		progress: '22',
		name: 'Chronicles of Heavenly Demon',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		name: 'City of Sanctuary',
		progress: '51',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		progress: '39',
		name: 'Dr. Player',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		name: 'Heavenly Martial God',
		progress: '23',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		name: 'Hero? I Quit A Long Time Ago.',
		progress: '151',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		progress: '15',
		name: 'I Have Max Level Luck',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		progress: '37',
		name: 'Infinite Apostles And Twelve War Girls',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		progress: '18',
		name: 'Kanchigai No Atelier Meister',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		name: "Library Of Heaven's Path",
		progress: '164',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		progress: '42',
		name: 'Lonely Attack On A Different World',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		name: 'Maou-Sama No Machizukuri! ~Saikyou No Dungeon Wa Kindai Toshi~',
		progress: '39',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		name: 'Murabito Desu Ga Nani Ka?',
		progress: '38',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		name: 'Murim Login',
		progress: '58',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		name: 'Overbearing Tyrant',
		progress: '40',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		progress: '18',
		name: 'Pick Me Up, Infinite Gacha',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		progress: '161',
		name: 'Player Reborn',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		name: 'Ranker’s Return',
		progress: '18',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		name: 'Regressor Instruction Manual',
		progress: '42',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		progress: '?',
		name: 'Reincarnation Of The Strongest Sword God',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		progress: '25',
		name: 'Return to Player',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		name: 'Solo Spell Caster',
		progress: '21',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		name: 'Super Evolution',
		progress: '21',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		name: 'The Boxer',
		progress: '50',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		progress: '147',
		name: 'The Girl from Random Chatting',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		name: 'The Hero Returns',
		progress: '33',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		name: 'The Hunter',
		progress: '253',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		progress: '19',
		name: 'The Newbie is Too Strong',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		progress: '51',
		name: 'The Rebirth Of An 8Th Circled Wizard',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		name: 'The Rebirth Of The Demon God',
		progress: '78',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		progress: '?',
		name: 'The Return of the Crazy Demon',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		name: 'The Villainous Warrior',
		progress: '4',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		progress: '25',
		name: 'The World After The End',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		progress: '103',
		name: 'Ultimate Soldier',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		name: 'Ultimiter',
		progress: '161',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		name: 'Wandering Warrior of Wudang',
		progress: '?',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'E',
		name: 'World’s Strongest Troll',
		progress: '18',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'F',
		progress: '2',
		name: 'Crazy Leveling System',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'F',
		progress: '68',
		name: 'Crimson Karma',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'F',
		name: 'Eleceed',
		progress: '?',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'F',
		progress: '?',
		name: 'Ending Maker',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'F',
		name: 'F-Class Destiny Hunter',
		progress: '9',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'F',
		progress: '?',
		name: 'I Am the Fated Villain',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'F',
		name: 'I Became a Renowned Family’s Sword Prodigy',
		progress: '?',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'F',
		name: 'Insanely-Talented Player',
		progress: '3',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'F',
		progress: '5',
		name: 'Lord of Mana',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'F',
		name: 'Mr Devourer, Please Act Like a Final Boss',
		progress: '1',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'F',
		progress: '13',
		name: 'Necromancer’s Evolutionary Traits',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'F',
		progress: '3',
		name: 'Star Instructor, Master Baek',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'F',
		name: 'Sword Fanatic Wanders Through The Night',
		progress: '3',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'F',
		progress: '12',
		name: 'Talent-Swallowing Magician',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'F',
		progress: '?',
		name: 'The Novel’s Extra (Remake)',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'F',
		progress: '14',
		name: 'The Return of the Prodigious Swordmaster',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'F',
		progress: '8',
		name: 'Trash of the Count’s Family',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'F',
		progress: '2',
		name: 'Weak hero',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'F',
		progress: '7',
		name: 'Worn and Torn Newbie',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'F',
		name: 'Worthless Regression',
		progress: '3',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'F',
		name: 'Your Talent is Mine',
		progress: '13',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'X',
		name: 'Hunter x Hunter',
		progress: '341',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'X',
		name: 'Kenja No Mago',
		progress: '52',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'X',
		progress: '67',
		name: 'Mushoku Tensei - Isekai Ittara Honki Dasu',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'X',
		progress: '1009',
		name: 'One Piece',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'unknown',
		name: 'Hoarding in Hell',
		progress: '',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'unknown',
		name: 'I Killed an Academy Player',
		progress: '',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'unknown',
		progress: '',
		name: 'I’m Not a Regressor',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'unknown',
		name: 'Regressor of the Fallen family',
		progress: '',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'unknown',
		name: 'Regressor’s Life After Retirement',
		progress: '',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'unknown',
		name: 'Reincarnated Escort Warrior',
		progress: '',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'unknown',
		progress: '',
		name: 'Star-Embracing Swordmaster',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'unknown',
		progress: '',
		name: 'Steel-Eating Player',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'unknown',
		progress: '',
		name: 'The Blood Knight’s Villains',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'unknown',
		name: 'The Extra is Too Strong',
		progress: '',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'unknown',
		progress: '',
		name: 'The Heavenly Demon’s Descendant',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'unknown',
		progress: '',
		name: 'The Priest of Corruption',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'unknown',
		progress: '',
		name: 'The Reincarnated Assassin is a Genius Swordsman',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'unknown',
		name: 'To Hell With Being A Saint, I’m A Doctor',
		progress: '',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
]
