import { ItemDto } from 'stores/FirebaseStore'
import { Timestamp } from 'firebase/firestore'

export const moviesData: ItemDto[] = [
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		progress: '3',
		name: 'Alvin And The Chipmunks',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		name: 'Ant-Man',
		progress: '2',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		progress: '4',
		name: 'Avengers',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		name: 'Big Hero 6',
		progress: '2014',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		name: 'Deadpool',
		progress: '2',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		name: 'Dungeons & Dragons: Honor Among Thieves',
		progress: '2023',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		progress: '2',
		name: 'Escape Plan',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		progress: '9',
		name: 'Fast And Furious',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		name: 'How To Train Your Dragon',
		progress: '3',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		progress: '6',
		name: 'Mission Impossible',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		progress: '2014',
		name: 'Non Stop',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		progress: '2',
		name: 'Now You See Me',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		name: 'Rampage',
		progress: '2018',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		name: 'Rise of the Planet of the Apes',
		progress: '3',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		name: 'Step Up',
		progress: '6',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		progress: '5',
		name: 'Taxi',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
]
