import { ItemDto } from 'stores/FirebaseStore'
import { Timestamp } from 'firebase/firestore'

export const seriesData: ItemDto[] = [
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		name: 'Arcane',
		progress: '1',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		name: 'Limitless',
		progress: '1',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		name: 'Prison Break',
		progress: '5',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'S',
		progress: '6',
		name: 'Silicon Valley',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: 'Game Of Thrones',
		progress: '8',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: "Marvel's The Punisher",
		progress: '2',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		progress: '23',
		name: 'South Park',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'A',
		name: 'Step up: High Water',
		progress: '2',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		name: 'Nikita',
		progress: '4',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		progress: '2',
		name: 'No Good Nick',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'B',
		name: 'Rick and Morty',
		progress: '',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'C',
		progress: '1',
		name: 'Loki',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'C',
		name: 'My Name',
		progress: '1',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'C',
		name: 'Squid Game',
		progress: '1',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'C',
		name: 'The 100',
		progress: '6',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'D',
		name: 'Fate The Winx Saga',
		progress: '1',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'D',
		name: 'Into The Badlands',
		progress: '3',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'D',
		name: 'Invincible',
		progress: '1',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'D',
		name: 'The Boys',
		progress: '3',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'D',
		name: 'The Simpsons',
		progress: '29',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
	{
		userId: 'JiARetGkGiRwsFcqe81xlQWZ4SA3',
		rank: 'D',
		progress: '2',
		name: 'Young Sheldon',
		created: Timestamp.fromDate(new Date()),
		updated: null,
	},
]
